name: Build Flutter Windows EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter Windows EXE
        run: flutter build windows --release

      - name: Build OpenDrawer.exe from C#
        run: dotnet publish OpenDrawer/OpenDrawer.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o windows

      - name: Copy OpenDrawer.exe to output
        run: copy windows\OpenDrawer.exe build\windows\x64\runner\Release\OpenDrawer.exe

      - name: Confirm OpenDrawer.exe exists
        run: dir build\windows\x64\runner\Release\OpenDrawer.exe

      - name: List final output folder
        run: dir build\windows\x64\runner\Release

      - name: Upload Windows EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/windows/x64/runner/Release
