name: Build Windows EXE

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Or your target version

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my_flutter_app_windows
          path: build/windows/runner/Release/
